name: run_track
description: "My final year project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  location: ^8.0.1
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  shared_preferences: ^2.2.4
  image_picker: ^1.2.0
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.5.0
  google_sign_in: ^6.2.1 # Google sign in
  rxdart: ^0.27.7
  path_provider: ^2.1.2
  geocoding: ^4.0.0
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/RunTracK-app-icon-round_launcher.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/l10n/
    - assets/background-start.jpg
    - assets/runtrack-app-icon-round.png
    - assets/background-first.jpg
    - assets/DefaultProfilePhoto.png
    - assets/google-icon.png
    - assets/appBg1.jpg
    - assets/appBg2.jpg
    - assets/appBg3.jpg
    - assets/appBg4.jpg
    - assets/appBg5.jpg
    - assets/appBg6.jpg
